version: '3.8'
services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner-http
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner_config:/etc/gitlab-runner
    networks:
      - gitlab-network
    depends_on:
      - gitlab

volumes:
  runner_config:

networks:
  gitlab-network:
    external: true
    name: gitlab-server_gitlab-network